using NetCore.Models;

namespace NetCore.Repositories
{
    public class MovieRepository
    {
        public static List<Movie> Movies = new()
        {
           
            new()
            {
                Id=1,
                Title="Eternals",
                Description="Eternals is a 2021 American superhero film based on the Marvel Comics race of the same name. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the 26th film in the Marvel Cinematic Universe (MCU). The film is directed by Chloé Zhao, who wrote the screenplay with Patrick Burleigh, Ryan Firpo, and Kaz Firpo. It stars an ensemble cast including Gemma Chan, Richard Madden, Kumail Nanjiani, Lia McHugh, Brian Tyree Henry, Lauren Ridloff, Barry Keoghan, Don Lee, Harish Patel, Kit Harington, Salma Hayek, and Angelina Jolie. In the film, the Eternals, immortal alien beings, emerge from hiding after thousands of years to protect Earth from their ancient counterparts, the Deviants.\r\n\r\nIn April 2018, Marvel Studios president Kevin Feige announced that a film based on the Eternals had begun development, with Ryan and Kaz Firpo hired to write the script in May. Zhao was set to direct the film by late September, and was given significant creative freedom with the film, which resulted in filming on location more than previous MCU films. Zhao rewrote the screenplay, to which Burleigh was later reported to have also contributed. Principal photography took place from July 2019 to February 2020, at Pinewood Studios as well as on location in London and Oxford, England, and in the Canary Islands.\r\n\r\nEternals premiered in Los Angeles on October 18, 2021, and was released in the United States on November 5, as part of Phase Four of the MCU. The film grossed $402 million worldwide. It received mixed reviews from critics, who praised its themes and visuals, but criticized its screenplay, pacing, runtime, and character development.",
                Rating=6.8
            },
            new()
            {
                Id=2,
                Title="Dune",
                Description="Dune (titled onscreen as Dune: Part One) is a 2021 American epic science fiction film directed by Denis Villeneuve from a screenplay by Villeneuve, Jon Spaihts, and Eric Roth. It is the first part of a two-part adaptation of the 1965 novel by Frank Herbert, primarily covering the first half of the book. Set in the distant future, the film follows Paul Atreides as his family, the noble House Atreides, is thrust into a war for the deadly and inhospitable desert planet Arrakis. The ensemble cast includes Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Josh Brolin, Stellan Skarsgård, Dave Bautista, Stephen McKinley Henderson, Zendaya, David Dastmalchian, Chang Chen, Sharon Duncan-Brewster, Charlotte Rampling, Jason Momoa, and Javier Bardem.\r\n\r\nThe film is the second theatrical adaptation of Dune following David Lynch's 1984 film, which was a critical and commercial failure, and the third adaptation overall following both the David Lynch film and John Harrison's 2000 miniseries. After an unsuccessful attempt by Paramount Pictures to produce a new adaptation, Legendary Entertainment acquired the Dune film and TV rights in 2016, with Villeneuve signing on as director in February 2017. Production contracts were only secured for the first film, relying on its success before a second film would be greenlit after the first film's release. Filming took place from March to July 2019 at locations including Budapest, Jordan, Norway, and Abu Dhabi.\r\n\r\nDune was originally scheduled for a late 2020 release, but it was delayed by the COVID-19 pandemic. The film premiered the following year at the 78th Venice International Film Festival on September 3, 2021, ahead of its international release on September 15, 2021. It was then released in United States theaters and streaming on HBO Max on October 22. The film received praise from critics for its visuals, musical score, ambition, performances, cinematography, direction, characters, and technical innovation, as well as for its faithfulness to the source material. It grossed $401 million worldwide on a production budget of $165 million. Organizations such as the National Board of Review and the American Film Institute named Dune as one of the top 10 films of 2021. Among its numerous awards and nominations, it received 10 nominations at the 94th Academy Awards, including Best Picture and Best Adapted Screenplay, and won the most awards of the ceremony with six: Best Sound, Best Original Score, Best Film Editing, Best Production Design, Best Visual Effects, and Best Cinematography. A sequel, Dune: Part Two, is set to be released on November 17, 2023.",
                Rating=6.3
            },
            new()
            {
                Id=3,
                Title="The Harder They Fall",
                Description="The Harder They Fall is a 2021 American Western film directed by Jeymes Samuel, who co-wrote the screenplay with Boaz Yakin. The film stars Jonathan Majors, Idris Elba, Zazie Beetz, Regina King, Delroy Lindo, Lakeith Stanfield, RJ Cyler, Danielle Deadwyler, Edi Gathegi, and Deon Cole. It is one of few Westerns whose principal cast members are all Black. Its characters are loosely based on real cowboys, lawmen, and outlaws of the nineteenth-century American West.\r\n\r\nThe Harder They Fall premiered at the BFI London Film Festival on October 6, 2021.[2] It received a limited release on October 22, 2021, prior to streaming on Netflix on November 3. The film received generally positive reviews for its ensemble cast as well as Samuel's direction and score.",
                Rating=6.4
            },
            new()
            {
                Id=4,
                Title="No Time To Die",
                Description="No Time to Die is a 2021 spy film and the twenty-fifth in the James Bond series produced by Eon Productions, starring Daniel Craig in his fifth and final portrayal of fictional British MI6 agent James Bond. It was directed by Cary Joji Fukunaga from a screenplay by Neal Purvis, Robert Wade, Fukunaga and Phoebe Waller-Bridge. Léa Seydoux, Ben Whishaw, Naomie Harris, Jeffrey Wright, Christoph Waltz, Rory Kinnear and Ralph Fiennes reprise their roles from previous films, with Rami Malek, Lashana Lynch, Billy Magnussen, Ana de Armas, David Dencik and Dali Benssalah also starring. In No Time to Die, Bond has left active service with MI6 and is recruited by the CIA to find a kidnapped scientist, which leads to a showdown with a powerful adversary.\r\n\r\nDevelopment began in 2016. It is the first Bond film distributed by Universal Pictures, which acquired international distribution rights following the expiration of Sony Pictures' contract after the release of Spectre in 2015. United Artists Releasing holds the rights for North America, as well as worldwide digital and television rights; Universal also holds the worldwide rights for physical home media. Danny Boyle was originally attached to direct and co-write the screenplay with John Hodge. Both left in August 2018 due to creative differences, and Fukunaga was announced as Boyle's replacement one month later. Most of the cast had signed by April 2019. Principal photography took place from April to October 2019. Billie Eilish performed the theme song \"No Time to Die\", while Hans Zimmer scored the film.\r\n\r\nAfter being delayed by Boyle's departure and later by the COVID-19 pandemic, No Time to Die premiered globally at the Royal Albert Hall in London on 28 September 2021. It was released in cinemas on 30 September 2021 in the United Kingdom and on 8 October 2021 in the United States. The film received positive reviews and has grossed over $774 million worldwide, making it the fourth-highest-grossing film of 2021. In addition to this, it had earned several other box-office record achievements, including becoming the third-highest-grossing film of all time in the UK. The film garnered several awards and nominations. These included five nominations at the 75th British Academy Film Awards, with a win for Best Editing, and three nominations at the 94th Academy Awards, with a win for Best Original Song (by Eilish and Finneas O'Connell). This became the third consecutive Bond theme song to win that category after Skyfall (2012) and Spectre (2015).[4]",
                Rating=6.0
            },
            new()
            {
                Id=5,
                Title="Red Notice",
                Description="FeatureRed Notice is a 2021 American action comedy film written, directed, and produced by Rawson Marshall Thurber and Dwayne Johnson, who also stars in the film alongside Ryan Reynolds and Gal Gadot and Ritu Arya. It marks the third collaboration between Thurber and Johnson, following Central Intelligence (2016) and Skyscraper (2018). In the film, an FBI agent reluctantly teams up with a renowned art robber in order to catch an even more notorious robber.\r\n\r\nOriginally planned for release by Universal Pictures, the film was acquired by Netflix for distribution.[2] It began a limited theatrical release on November 5, 2021,[3] before digitally streaming on the platform on November 12, 2021, where it received mixed reviews from critics and audience, who praised the performances of the cast (particularly Reynolds and Johnson), action sequences, and humor, but criticized the lack of originality.\r\n\r\nThe film became the most-watched film in its debut weekend, as well as the most-watched film within 28 days of release on the platform in Netflix. It also became the 5th most-streamed movie title of 2021.[4] Two sequels are in development and will be filmed back-to-back with Johnson, Reynolds, Gadot, and Thurber expected to return.[5][6]",
                Rating=6.8
            },
            
        };
    }
}
